const PERMISSIONS = {
  // Bulk import users, delete and update users
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  // Departments management
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  MANAGE_DEPARTMENT_REQUEST: "MANAGE_DEPARTMENT_REQUEST",

  // Event management
  VIEW_EVENTS_FOR_ALL_DEPARTMENT: "VIEW_EVENTS_FOR_ALL_DEPARTMENT",

  //Semester Permission
  CREATE_SEMESTER: "CREATE_SEMESTER",
  UPDATE_SEMESTER: "UPDATE_SEMESTER",
  DELETE_SEMESTER: "DELETE_SEMESTER",

  //Location Permissions
  CREATE_LOCATION: "CREATE_LOCATION",
  DELETE_LOCATION: "DELETE_LOCATION",

  MUTATE_REQUISITION: "MUTATE_REQUISITION",

  VIEW_ALL_REQUISITION: "VIEW_ALL_REQUISITION",
  VIEW_MY_REQUISITION: "VIEW_MY_REQUISITION",
  VIEW_DEPARTMENT_REQUISITION: "VIEW_DEPARTMENT_REQUISITION",

  VERIFY_REJECT_LEVEL_1: "VERIFY_REJECT_LEVEL_1",
  VERIFY_REJECT_LEVEL_2: "VERIFY_REJECT_LEVEL_2",
  VERIFY_REJECT_LEVEL_3: "VERIFY_REJECT_LEVEL_3",

  // Certificate
  GENERATE_CERTIFICATE: "GENERATE_CERTIFICATE",
};

const READABLE_PERMISSIONS = {
  // Bulk import users, delete and update users
  CREATE_USER: "Add Users to the system",
  UPDATE_USER: "Update user roles",
  DELETE_USER: "Remove users",

  // Departments management
  CREATE_DEPARTMENT: "Add Departments",
  UPDATE_DEPARTMENT: "Update department details",
  DELETE_DEPARTMENT: "Delete department",
  MANAGE_DEPARTMENT_REQUEST: "Manage department requests",

  // Event management
  VIEW_EVENTS_FOR_ALL_DEPARTMENT: "Access events of all departments",

  //Semester Permission
  CREATE_SEMESTER: "Add Semester",
  UPDATE_SEMESTER: "Update Semester Details",
  DELETE_SEMESTER: "Delete Semester",

  //Location Permissions
  CREATE_LOCATION: "Add location shortcut",
  DELETE_LOCATION: "Remove location shortcut",

  //Procurement Permissions
  MUTATE_REQUISITION: "Create/Update/Delete Requisition",

  VIEW_ALL_REQUISITION: "View All Requisitions",
  VIEW_MY_REQUISITION: "View My Requisitions",
  VIEW_DEPARTMENT_REQUISITION: "View Department Requisitions",

  VERIFY_REJECT_LEVEL_1: "Verify/Reject Requisition Level 1",
  VERIFY_REJECT_LEVEL_2: "Verify/Reject Requisition Level 2",
  VERIFY_REJECT_LEVEL_3: "Verify/Reject Requisition Level 3",

  // Certificate Permissions
  GENERATE_CERTIFICATE: "Generate Certificate",
};

const PERMISSION_GROUPS = {
  "User permissions": [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
  ],
  "Department permissions": [
    PERMISSIONS.CREATE_DEPARTMENT,
    PERMISSIONS.UPDATE_DEPARTMENT,
    PERMISSIONS.DELETE_DEPARTMENT,
    PERMISSIONS.MANAGE_DEPARTMENT_REQUEST,
  ],
  "Event permissions": [PERMISSIONS.VIEW_EVENTS_FOR_ALL_DEPARTMENT],
  "Semester permissions": [
    PERMISSIONS.CREATE_SEMESTER,
    PERMISSIONS.UPDATE_SEMESTER,
    PERMISSIONS.DELETE_SEMESTER,
  ],
  "Location permissions": [
    PERMISSIONS.CREATE_LOCATION,
    PERMISSIONS.DELETE_LOCATION,
  ],
  "Procurement Permissions": [
    PERMISSIONS.MUTATE_REQUISITION,
    PERMISSIONS.VIEW_ALL_REQUISITION,
    PERMISSIONS.VIEW_MY_REQUISITION,
    PERMISSIONS.VIEW_DEPARTMENT_REQUISITION,
    PERMISSIONS.VERIFY_REJECT_LEVEL_1,
    PERMISSIONS.VERIFY_REJECT_LEVEL_2,
    PERMISSIONS.VERIFY_REJECT_LEVEL_3,
  ],

  "Certificate Permissions": [PERMISSIONS.GENERATE_CERTIFICATE],
};

const PROCUREMENT_PERMISSIONS = [
  "MUTATE_REQUISITION",

  "VIEW_ALL_REQUISITION",
  "VIEW_MY_REQUISITION",
  "VIEW_DEPARTMENT_REQUISITION",

  "VERIFY_REJECT_LEVEL_1",
  "VERIFY_REJECT_LEVEL_2",
  "VERIFY_REJECT_LEVEL_3",
];

export {
  PERMISSIONS,
  READABLE_PERMISSIONS,
  PERMISSION_GROUPS,
  PROCUREMENT_PERMISSIONS,
};
